[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
OpenCL = "08131aa3-fb12-5dee-8b74-c09406e224a2"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
VortexPasta = "3d0f1e53-df37-477e-a492-0d33e6039c24"
pocl_jll = "627d6b7a-bbe6-5189-83e7-98cc0a5aeadd"

[sources]
OpenCL = {rev = "jip/atomic_float", url = "https://github.com/jipolanco/OpenCL.jl.git"}
