[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
ThreadPinning = "811555cd-349b-4f26-b7bc-1f208b848042"
VortexPasta = "3d0f1e53-df37-477e-a492-0d33e6039c24"
